### PR TITLE
currency-convertor::assignment

### PR DESCRIPTION
**Pull request by chandanGr**

### CODE REVIEW

**Comment by chandanGr** [comment]
There were few issues in the BE....

- CORS error was not handled

- there is GET request instead of PUT request

I have fixed those changes and pushed a patch in the same PR

**Review by AdithyaBhat17 — COMMENTED** [review]
Hi, I'm not accepting any PRs for this repository. Thanks for raising these issues but these were done on purpose.

**Comment by chandanGr** [comment]
> Hi, I'm not accepting any PRs for this repository. Thanks for raising these issues but these were done (or not handled) on purpose.

how should send my assignment then?

**Comment by AdithyaBhat17** [comment]
> how should I send my assignment then?

Please share your Github repository link to the HR via email.

**Comment by chandanGr** [comment]
> > how should I send my assignment then?
> 
> Please share your Github repository link to the HR via email.

Thanks

**Pull request closed without merging**
